### ISSUE TITLE
How to make waveform full width?

### ISSUE THREAD

**Issue by FritzHsiao** [VideoFlint/VIWaveformView#1]
Hi,
Thanks for this library.
Is there any way to make the waveform full width like VIWaveformView? 
Some of my audios looks short in waveform.

Thanks

**Comment by vitoziv** [comment]
You can set VIWaveformView's minWidthPerSecond.  

As you need, your minWidthPerSecond would be: 
```
minWidthPerSecond = VIWaveformView.width / audio.duration
```
